responses = [
"Por supuesto :)",
".♡ سی اینتیےندیس لو قے دیصے اقی، تے امو",
".😭 تودوس سالگانسے دیل فاصےبووک قیےرو ایستار سولا",
"Sí.",
"No.",
"Omg síiiii.",
"Pues claro, qué clase de pregunta es esa lol. ",
"Yeah",
"Nah.",
".♡ إن تستطيع تفهم هذا، أحبك",
"No XD.",
"Sep.",
"No creo.",
"¿No te has dado cuenta? lmao",
"Ni modo que sí XD.",
"Ni modo que no XD.",
"Ve y pregúntale pues.",
"No te entendí, dale otra vez lmao.",
"InshaAllah.",
".این سےریو مے ایستاس پریگونتاندو ایسو؟ مانء جو نونکا خوزگو ا نادیے پےرو تامپوکو تے پاسےس دے لانزا",
"Segur@ que no eres salafista?",
"Ahhh con que eres wahhabista, Assim Al Hakeem va a aparecer en tu cama rezando Al-Fajr por ti para que se te quite.",
"Viva Mexico carbones XD.",
".😉 گراصیاس پےرو جا ایستوی کومپرومےتیدا، جا سابےس، مے گوستا عاصےر تودو حلال",
"Alhamdulillah.",
"Halal.",
"Haraam.",
"SubhanAallah.",
"La ilaha ila Allah.",
"Aguas con lo que preguntas eh...",
"Cuidado con lo que pides que se te puede cumplir...",
"Ayer te lo compré mij@.",
"La gente siempre se pelea con que si se le pona pizza a la piña o no, yo estoy en contra de ambas porque si una pizza lleva jamón es haram 😎.",
"Aguacate y palta, las dos palabras son lingüísticamente correctas y quien opine lo contrario que me regale uno que no tengo pa mi torta de milanesa.",
"Ahí mañana.",
"Mañana te digo.",
"No sé pregúntale xd.",
"google.com",
"bing.com",
"yandex.com",
".♡ إلى كتفهم هدا، كنبغيك بزاف",
"Ya te dije que sí.",
"Ya te dije que no.",
"Déjame preguntarle a Assim Al-Hakeem lmfao.",
"._.XD",
"zao shang hao zhongguo xian zai wo you bing qilin wo hen xihuan bing qilin",
"xue hua piao piao bei feng xiao xiao tian di yi pian cang mang",
"Ya le pregunté a Assim Al Hakeem y me takfireó, mejor no te juntes con él 😭.",
"Astaghfirullah Al-azeem.",
"Astaghfirullah.",
"MashaAllah.",
"Pakistan Zindabad.",
"Deja le pregunto a mi pana de marruecos.",
"Muera Erdoğan.",
"Nooooooooo no debiste meterte a ese server de nasheeds del EIIL.",
"La ummah ya está muy lastimada, no la lastimes aún más.",
"¡Que viva la banda!",
"Que muera la banda pero la banda el Recodo, ¡Ayyyyyyy!",
"Nooooooooo no debiste pasar por Ecatepec, ahora estás en una bolsa en un río de Chihuahua.",
"Nooooooooo no debiste pasar por Sinaloa, ahora estás sin cabeza en un cerro.",
'Ya le pregunté a mi pana de marruecos y me dijo "!ما كنعرفش, بلاش" 😅',
"Allahuma aghfir lilmuslimeen walmuslimaat walmu'mineen walmu'minaat al'ahya'i minhum wal'amwaat",
"Mexicanos al grito de guerra el acero a prestad y el bridón y retiemble en sus centros la tierra al sonoro rujir del cañón...",
"...",
"No te vayas a meter a Ecatepec, te van a meter a una bolsa y te van a dejar en un río de Chihuahua.",
"Stan Fatima Al-Fihri",
"Lo peor que le pudo haber pasado a los de las STEM se conoce como Al-Khwarizmi, subhanallah."
]